# Build and push an image to ACR, setup notation and sign the image
name: sign-notation-trusted-signing

on:
  workflow_dispatch:
  
env:
  ACR_REGISTRY_NAME: wabbitregistry.azurecr.io          # example: myRegistry.azurecr.io
  ACR_REPO_NAME: hello-world                            # example: myRepo
  TAG: v1
  PLUGIN_NAME: azure-trustedsigning                     # DO NOT CHANGE
  PLUGIN_DOWNLOAD_URL: "https://raw.githubusercontent.com/yizha1/image-integrity/main/.github/plugin/notation-azure-trustedsigning_0.3.0-beta.1_linux_amd64.tar.gz"
  PLUGIN_CHECKSUM: 808b7fa45cfca0a0f400db33958a3d6aca37a73df2e77008fe149314344bfd11
  TSA_URL: http://timestamp.acs.microsoft.com/
  TSA_ROOT_CERT: .github/certs/msft-identity-verification-root-cert-authority-2020.crt
  TS_ACCOUNT_NAME: "yizha1-ts"                          # example: myAccount
  TS_CERT_PROFILE: "yizha1-cert-profile"                # example: myCertProfile
  TS_BASE_URL: "https://eus.codesigning.azure.net/"     # example: https://eus.codesigning.azure.net/
  NOTATION_EXPERIMENTAL: 1                              # [Optional] when set, use Referrers API in the workflow (Recommended)

jobs:
  notation-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
     # packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        id: prepare
        run: |
          echo "target_artifact_reference=${{ env.ACR_REGISTRY_NAME }}/${{ env.ACR_REPO_NAME }}:${{ env.TAG }}" >> "$GITHUB_ENV"
      
      # Log in to Azure with your service principal secret
      # - name: Azure login
      #  uses: Azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}
      # If you are using OIDC and federated credential, make sure to replace the above step with below:
      - name: Azure login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Log in to your ACR registry
      - name: ACR login
        run: |
            az acr login --name ${{ env.ACR_REGISTRY_NAME }}
      # Build and push an image to the registry
      # Use `Dockerfile` as an example to build an image
      - name: Build and push
        id: push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.target_artifact_reference }}
          build-args: |
            IMAGE_TAG={{ env.TAG }}
      # Get the manifest digest of the OCI artifact
      - name: Retrieve digest
        run: |
          echo "target_artifact_reference=${{ env.ACR_REGISTRY_NAME }}/${{ env.ACR_REPO_NAME }}@${{ steps.push.outputs.digest }}" >> "$GITHUB_ENV"
      
      # Install Notation CLI with the default version "1.0.0"
      - name: setup notation
        uses: notaryproject/notation-action/setup@v1.2.2
      
      # Sign your OCI artifact using private key stored in AKV
      - name: sign OCI artifact using key pair from AKV
        uses: notaryproject/notation-action/sign@v1
        with:
          timestamp_url: ${{ env.TSA_URL}}
          timestamp_root_cert: ${{env.TSA_ROOT_CERT }}
          plugin_name: ${{ env.PLUGIN_NAME }}
          plugin_url: ${{ env.PLUGIN_DOWNLOAD_URL }}
          plugin_checksum: ${{ env.PLUGIN_CHECKSUM }}
          key_id: ${{ env.TS_CERT_PROFILE }}
          target_artifact_reference: ${{ env.target_artifact_reference }}
          signature_format: cose
          plugin_config: |-
            accountName=${{ env.TS_ACCOUNT_NAME }}
            baseUrl=${{ env.TS_BASE_URL }}
            certProfile=${{ env.TS_CERT_PROFILE }}
      #    force_referrers_tag: 'true'
